---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailbox-server
  namespace: server-test
  labels:
    app: mailbox-server
    app.kubernetes.io/name: mailbox-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailbox-server
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { "name": "sdf-ad-ingest",
                  "namespace": "multus-system",
                  "ips": [ "172.24.8.217/24" ],
                  "gateway": [ "172.24.8.1" ] }
        ]'
      labels:
        app: mailbox-server
        app.kubernetes.io/name: mailbox-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: edu.stanford.slac.sdf.k8s.networking.multus
                operator: In
                values:
                - enable
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ext-load-balancer
      containers:
        - name: mailbox-server
          image: tidacs/softioc-python:v1.5
          ports:
          - containerPort: 5075
          - containerPort: 5076

---
apiVersion: v1
kind: Service
metadata:
  name: mailbox-service-tcp
  namespace: server-test
  annotations:
    metallb.universe.tf/allow-shared-ip: "mailbox-test-key"
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  ports:
  - port: 5075
    targetPort: 5075
    protocol: TCP
    name: mailbox-tcp
  selector:
    app: mailbox-server

---
apiVersion: v1
kind: Service
metadata:
  name: mailbox-service-udp
  namespace: server-test
  annotations:
    metallb.universe.tf/allow-shared-ip: "mailbox-test-key"
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  ports:
  - port: 5076
    targetPort: 5076
    protocol: UDP
    name: mailbox-udp
  selector:
    app: mailbox-server

